### ISSUE TITLE
Chrome driver version... still

### ISSUE THREAD

**Issue by bruno-barros** [konsulting/dusk-standalone#10]
I'm setted with "konsulting/dusk-standalone": "6.1.*"

After run `vendor/bin/dusk-updater update` I got this error message: `Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 104     
Current browser version is 103.0.5060.134 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

Any help to update (or downgrade) to avoid this?

**Comment by Keoghan** [comment]
Are you able to update your version of Chrome?

Otherwise you should be able to target a specific version by following instructions here: https://github.com/orchestral/dusk-updater

**Comment by bruno-barros** [comment]
Thanks @Keoghan 
I was able to use dusk-update do set the correct driver version.

**Comment by Keoghan** [comment]
Great!
