### ISSUE TITLE
problem with chrome version

### ISSUE THREAD

**Issue by gilsedawk** [konsulting/dusk-standalone#4]
I cannot use this package because it says unsupported chrome version:

> Tests\Browser\ExampleTest::testBrowseSite
> Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73
>   (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-64-generic x86_64)

Anything i can do to fix this?

**Comment by Keoghan** [comment]
hi @gilsedawk what version of Chrome are you trying to use? hopefully then I can point in the right direction - we might need to update chromedriver.

**Comment by gilsedawk** [comment]
its the default ubuntu 18 version so i guess 78.

As a work around i installed chrome 71 .deb i found somewhere and then it works.

**Comment by Keoghan** [comment]
OK, thanks. I think you will just have needed to run `vendor/bin/dusk-updater update` as in the link above.

**Comment by gilsedawk** [comment]
oh silly me.. its also mentioned in the readme i see now..

my bad.

thx!

**Comment by Keoghan** [comment]
No worries - hope it's useful :)
