### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by vituxre** [konsulting/dusk-standalone#6]
Is there a plan to update to latest dusk 6.x and latest chrome version 85?

**Comment by Keoghan** [comment]
Hi, I have added a new 6.x branch - waiting for Travis to complete :)

**Comment by simonhammes** [comment]
@Keoghan Any news on this? ;)

**Comment by Keoghan** [comment]
Hi @simonhammes, there is a 6.x branch for Dusk 6. Is there anotherr update you are seeking?

**Comment by simonhammes** [comment]
@Keoghan According to Packagist, the latest release is 5.0, which still uses PHPUnit 8 & facebook/php-webdriver. 
I would like to see another official release.

**Comment by Keoghan** [comment]
I have tagged 6.0
